export const AUTHENTICATE = "AUTHENTICATE";
export const UNAUTHENTICATE = "UNAUTHENTICATE";
export const IMAGEUPDATE = "IMAGEUPDATE";
export const UPDATEFULLNAMEANDBIO = "UPDATEFULLNAMEANDBIO";
export const UPDATESOCIALMEDIA = "UPDATESOCIALMEDIA";
export const DELETE_RESULT = "DELETE_RESULT";
